# This file was generated by GoReleaser. DO NOT EDIT.
cask "ps5-barcode-scanner" do
  name "ps5-barcode-scanner"
  desc "CLI tool to scan and process PS5 barcodes"
  homepage "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ps5-barcode-scanner"

  on_macos do
    on_intel do
      url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v#{version}/downloads/ps5-barcode-scanner_Darwin_x86_64.tar.gz"
      sha256 "ff26fa18fc946e776ab8a73f81ea18492a4b0a7c2282ad6e6b6bf8b710edb95a"
    end
    on_arm do
      url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v#{version}/downloads/ps5-barcode-scanner_Darwin_arm64.tar.gz"
      sha256 "450f542292a713630892484c1c927fffdad31e0c47140c19784a360ff5f53571"
    end
  end

  # No zap stanza required
end
