# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GopticonConnect < Formula
  desc "CLI tool to scan and process PS5 barcodes"
  homepage "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.0.3/downloads/homebrew-gopticon-connect_Darwin_x86_64.tar.gz"
    sha256 "7a4046a1c456df4543cb3f7cb2850a47bab4123406915b072960a90451e0d720"

    def install
      bin.install "homebrew-gopticon-connect"
    end
  end
  if Hardware::CPU.arm?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.0.3/downloads/homebrew-gopticon-connect_Darwin_arm64.tar.gz"
    sha256 "8037a2829d222d86e8e38924a17cf27a8c6dee5e2263ca2f6813d398c53a5c4d"

    def install
      bin.install "homebrew-gopticon-connect"
    end
  end
end
