# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GopticonConnect < Formula
  desc "CLI tool to scan and process PS5 barcodes"
  homepage "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.1.0/downloads/homebrew-gopticon-connect_Darwin_x86_64.tar.gz"
    sha256 "aca0783dd6b6f11e3f84f9d7cb8933bc433e18c0b103d43dd58a25c6dc0d7bdd"

    def install
      bin.install "homebrew-gopticon-connect"
    end
  end
  if Hardware::CPU.arm?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.1.0/downloads/homebrew-gopticon-connect_Darwin_arm64.tar.gz"
    sha256 "b73b5eba197bca86f5df8a5a03893d94c272ffaaeca2779159b44684d6e16e4b"

    def install
      bin.install "homebrew-gopticon-connect"
    end
  end
end
