# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GopticonConnect < Formula
  desc "CLI tool to scan and process PS5 barcodes"
  homepage "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner"
  version "0.2.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.2.4/downloads/ps5-barcode-scanner_Darwin_x86_64.tar.gz"
    sha256 "7cdf3c0251c39dbde175d1481d8fb7f8c33f450ffe3b5959dbef6e7cd24824fe"

    def install
      bin.install "gopticon-connect"
    end
  end
  if Hardware::CPU.arm?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.2.4/downloads/ps5-barcode-scanner_Darwin_arm64.tar.gz"
    sha256 "28ae69e8d0308dbfd18836d650ebf26cd587238f39e7f68deedf4c18e0326b42"

    def install
      bin.install "gopticon-connect"
    end
  end
end
