# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GopticonConnect < Formula
  desc "CLI tool to scan and process PS5 barcodes"
  homepage "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.1.2/downloads/ps5-barcode-scanner_Darwin_x86_64.tar.gz"
    sha256 "0de8e6800d81acde7d5f7e4bfe86317a33facf57a5a7751c7c94a9c5aa0a8382"

    def install
      bin.install "gopticon-connect"
    end
  end
  if Hardware::CPU.arm?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.1.2/downloads/ps5-barcode-scanner_Darwin_arm64.tar.gz"
    sha256 "48bd6e3e412770a423aed3f57f2bd6daa560e1249b852d3c92cd5a1c75c7ec78"

    def install
      bin.install "gopticon-connect"
    end
  end
end
