# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ps5BarcodeScanner < Formula
  desc "CLI tool to scan and process PS5 barcodes"
  homepage "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.0.3/downloads/ps5-barcode-scanner_Darwin_x86_64.tar.gz"
    sha256 "059688ad84cc7ad37a268883bf3ec1f4e378c7e016b90e74cbaccc283b21d3dd"

    def install
      bin.install "ps5-barcode-scanner"
    end
  end
  if Hardware::CPU.arm?
    url "https://gitlab.forge.hefr.ch/louis.pasquier/ps5-barcode-scanner/-/releases/v0.0.3/downloads/ps5-barcode-scanner_Darwin_arm64.tar.gz"
    sha256 "1da034851f7418c6f521f4797a0a7fd4d8e4da635a6b3f5276fea54bce6d8cd9"

    def install
      bin.install "ps5-barcode-scanner"
    end
  end
end
